version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3400:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      HOST: mysql-db
      USER: root
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE: ${DATABASE}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
